services:
  app:
    container_name: app
    build: ./docker/php
    volumes:
      - .:/var/www
      - ./docker/php/overrides.ini:/usr/local/etc/php/conf.d/overrides.ini

  nginx:
    image: nginx:1.27.4-bookworm
    container_name: nginx
    environment:
      - TZ=Asia/Tokyo
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www
    depends_on:
      - app
